#This will deploy the safe, Secure, tested, app to PROD server
name: deploy to Server

on:
    workflow_call:
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout code
              uses: actions/checkout@v4
            - name: Debug files
              run: |
                echo "Current directory:"
                pwd
                echo "Files in repo:"
                ls -R

            - name: Copy Docker Compose File
              uses: appleboy/scp-action@v1
              with:
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USER }}
                key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                source: "./docker-compose.yml"

            - name: SSH to Prod Server
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USER }}
                key: ${{ secrets.EC2_SSH_PRIVATE_KEY }} 
                  echo "SSH key found"
                script: |
                  echo "Starting Deployment"
                  mkdir -p /home/${{ secrets.EC2_SSH_USER }}/devops

                    





