# This is workflow name
name: hello sonali

# runs on a automatic trigger, whenever chnage is pushed to branch this process is [deployment]
on:
  push:    #if we use this then code will run every after commit and if dont want like that then simply use workflow_dispatch: 
    branches: [main]
    paths:     #So whenever push the code in the git branch and if it is related to html file thne only exection will get triggered
      - '**.html'
      - '**.yml'
  
#These are the jobs inside workflow
#Every job needs separate runner, its called parallelism [Ti means at a time multiple jobs should run individually]
jobs:

  #these is name of the job
  greet:

    #This is github running, each job runs on the runner

    runs-on: ubuntu-latest
    steps: 
      - name: say hello to users
        run: echo "Hello All"

      - name: say hello to username
        run: echo "Hello USERS"

  #this is the name of the job
  details:
    runs-on: ubuntu-latest
    steps:
      - name: Show what is the version of the docker and python etc
        run: docker --version && python --version
  
  
 
