# This is workflow name
name: hello sonali

# runs on a trigger
on:
  push: 
    branches: [main]

#These are the jobs inside workflow
jobs:

  #these is name of the job
  greet:

    #This is github running, each job runs on the runner

    runs-on: ubuntu-latest
    steps: 
      - name: say hello to users
        run: echo "Hello All"

      - name: say hello to username
        run: echo "Hello USERS"
