#API keys, Sensitive data, Credentials we hardcode in the code and forget it to preven this we use tool name as GitLeaks
#GitLeaks is the tool look all the commit history and check all security vulnerabilities issues, API keys and flag/notify to us 
name: Secrets Scans

on: 
    workflow_call:
jobs:
    secrets-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4  #it will always bring the latest code 
              with:
                fetch-depth: 0
            
            - name: Run Gitleaks Scanner
              uses: gitleaks/gitleaks-action@v2 #gitleaks uses the github token and scan the code and tells us all the code vulnerabilities and issues
              env: 
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #Github Actions when runs any workflow at the time creates secret t0oken byitself and gives that secret token to the runner, After this, That runner uses this token and acdess our code  
                #GITLEAKS_LICENSE: is needed when you are working in big orgnization, and not in personal account 

#Note: SOC2 [System and Orgnization Cintrol]: GitHub is the SIC2 compliance standard developed by the AICPA for service providers to ensure secure management of the customer data based on five trust service criteria: Security, Availability, Processing integrety, Confidentiality and privacy etc It is essential for SaaS companies and cloud service providers to demonstrate trustworthiness, build credibility and satisfy enterprice vender security requirements.
#Gitleaks is the safe which we have got from the gitrhub marketplace this is SAST tool for detecting and preventing hardcoded secrets like Passwords, API keys, and tokens in the git repos whether it is past or present repo OR code, This is easy to use all in one solution for detecting and preventing hardcoded secrets like Passwords, API keys, and tokens in the git repos
